before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - # Build mdbook
  - pushd mdbook
  - bash build-push-mdbook.sh

#jobs:
#  include:
#    if: branch = master
#    - stage: build docker images
#      before_script:
#      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#      script:
#      - cd mdbook
#      - build-push-mdbook.sh
