before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - # Build mdbook
  - pushd mdbook
  - bash build-push-mdbook.sh
  - popd
  - # Build python
  - pushd python
  - bash build-push-python.sh
  - popd
